/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-phonetic.h
 #	source generated by 4D Plugin Wizard
 #	Project : phonetic
 #	author : miyako
 #	2020/06/02
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_PHONETIC_H
#define PLUGIN_PHONETIC_H

#include "4DPluginAPI.h"

#if VERSIONWIN
#include "msime.h"
#endif

#include "support/4DPlugin-JSON.h"

#include "C_TEXT.h"

#pragma mark -

void Phonetic(PA_PluginParameters params);
void Phonetics(PA_PluginParameters params);

#endif /* PLUGIN_PHONETIC_H */
