/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : phonetic
 #	author : miyako
 #	2016/08/02
 #
 # --------------------------------------------------------------------------------*/

#include "msime.h"

// --- phonetic
void Phonetic(sLONG_PTR *pResult, PackagePtr pParams);
